import React from 'react'
import { keyId } from '../../Utils/razorpayAPI'

const RazorPayForm = () => {



    //docs: https://razorpay.com/docs/payment-gateway/quick-integration/#step-2-pass-order-id-and-other-options
    return (
        <div>
            <form action="https://www.example.com/payment/success/" method="POST">
                <script src="https://checkout.razorpay.com/v1/checkout.js"
                    data-key={keyId} // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                    data-amount="29935" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                    data-order_id="order_CgmcjRh9ti2lP7"// Replace with the order_id generated by you in the backend.
                    data-buttontext="Pay with Razorpay"
                    data-name="Acme Corp"
                    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
                    data-image="https://example.com/your_logo.jpg"
                ></script>
                    <input type="hidden" custom="Hidden Element" name="hidden" />
            </form>
        </div>
    )
}

export default RazorPayForm
